meta_product_name: "Product Name"
meta_title: "SplitHouse - Mon incroyable résidence secondaire"
meta_description: "Découvrir ma prochaine résidence secondaire"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
